#!/usr/bin/env bash

set -euo pipefail

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
SANDBOX_PORT="${SANDBOX_PORT:-6865}"
LEDGER_ID="${LEDGER_ID:-sandbox}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DAML_DIR="${REPO_ROOT}/daml"
LOG_DIR="${REPO_ROOT}/log"
mkdir -p "${LOG_DIR}"

SANDBOX_LOG="${LOG_DIR}/sandbox-bootstrap.log"
SANDBOX_PID_FILE="${LOG_DIR}/sandbox-bootstrap.pid"
ENV_FILE="${REPO_ROOT}/dev-env.sh"

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
log() {
  printf '[bootstrap] %s\n' "$*" >&2
}

wait_for_ledger() {
  local retries=30
  for ((i=1; i<=retries; i++)); do
    if daml ledger list-parties --host localhost --port "${SANDBOX_PORT}" >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done
  return 1
}

# -----------------------------------------------------------------------------
# 1. Build DAR
# -----------------------------------------------------------------------------
log "Building DAR in ${DAML_DIR}"
(cd "${DAML_DIR}" && daml clean && daml build)

# -----------------------------------------------------------------------------
# 2. Start sandbox (if not already running)
# -----------------------------------------------------------------------------
if ! daml ledger list-parties --host localhost --port "${SANDBOX_PORT}" >/dev/null 2>&1; then
  log "Starting sandbox on port ${SANDBOX_PORT}"
  (cd "${DAML_DIR}" && nohup daml sandbox --port "${SANDBOX_PORT}" >"${SANDBOX_LOG}" 2>&1 & echo $! > "${SANDBOX_PID_FILE}")
  if ! wait_for_ledger; then
    log "Sandbox did not become ready; see ${SANDBOX_LOG}"
    exit 1
  fi
else
  log "Sandbox already running on port ${SANDBOX_PORT}"
fi

# -----------------------------------------------------------------------------
# 3. Upload DAR and run scripts
# -----------------------------------------------------------------------------
log "Uploading DAR to sandbox"
(cd "${DAML_DIR}" && daml ledger upload-dar --host localhost --port "${SANDBOX_PORT}" ./.daml/dist/erc20-canton-0.0.1.dar)

log "Running bootstrap scripts"
(cd "${DAML_DIR}" && daml script --ledger-host localhost --ledger-port "${SANDBOX_PORT}" --dar ./.daml/dist/erc20-canton-0.0.1.dar --script-name ERC20.Script:test)
(cd "${DAML_DIR}" && daml script --ledger-host localhost --ledger-port "${SANDBOX_PORT}" --dar ./.daml/dist/erc20-canton-0.0.1.dar --script-name ERC20.Inspect:balancesOk)

log "Ensuring Issuer/Alice/Bob parties exist"
daml ledger allocate-parties --host localhost --port "${SANDBOX_PORT}" Issuer Alice Bob >/dev/null

# -----------------------------------------------------------------------------
# 4. Compute environment exports
# -----------------------------------------------------------------------------
log "Computing helper environment variables"

ERC20_PKG_ID=$(
  daml damlc inspect-dar "${DAML_DIR}/.daml/dist/erc20-canton-0.0.1.dar" |
    grep -m1 'erc20-canton-0.0.1-' |
    sed -E 's|.*erc20-canton-0.0.1-([0-9a-f]+).*|\1|'
)

ISSUER_PARTY=$(
  daml ledger list-parties --host localhost --port "${SANDBOX_PORT}" |
    awk -F"'" '/displayName = "Issuer"/ {print $2; exit}'
)
ALICE_PARTY=$(
  daml ledger list-parties --host localhost --port "${SANDBOX_PORT}" |
    awk -F"'" '/displayName = "Alice"/ {print $2; exit}'
)
BOB_PARTY=$(
  daml ledger list-parties --host localhost --port "${SANDBOX_PORT}" |
    awk -F"'" '/displayName = "Bob"/ {print $2; exit}'
)

if [[ -z "${ISSUER_PARTY}" || -z "${ALICE_PARTY}" || -z "${BOB_PARTY}" ]]; then
  log "Failed to resolve party identifiers; aborting."
  exit 1
fi

cat > "${ENV_FILE}" <<EOF
# Generated by scripts/bootstrap.sh
export LEDGER_ID="${LEDGER_ID}"
export SANDBOX_PORT="${SANDBOX_PORT}"
export ERC20_PKG_ID="${ERC20_PKG_ID}"
export ISSUER_PARTY="${ISSUER_PARTY}"
export ALICE_PARTY="${ALICE_PARTY}"
export BOB_PARTY="${BOB_PARTY}"
EOF

log "Environment exports written to ${ENV_FILE}"
log "Bootstrap complete."
